
import sys
from awsglue.transforms import *
  from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from awsglue import DynamicFrame


def sparkSqlQuery(glueContext, query, mapping, transformation_ctx) -> DynamicFrame:
  for alias, frame in mapping.items():
  frame.toDF().createOrReplaceTempView(alias)
result = spark.sql(query)
return DynamicFrame.fromDF(result, glueContext, transformation_ctx)


args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# Script generated for node S3 bucket
occ_node = glueContext.create_dynamic_frame.from_catalog(
  database="databox", table_name="occ_index_record", transformation_ctx="occ_node"
)

sampling_node = glueContext.create_dynamic_frame.from_catalog(
  database="databox",
  table_name="sampling",
  transformation_ctx="sampling_node",
)

occ_fields = {"strings['abcdTypeStatus']": "abcdTypeStatus",
  "strings['acceptedNameUsage']": "acceptedNameUsage",
  "strings['acceptedNameUsageID']": "acceptedNameUsageID",
  "strings['accessRights']": "accessRights",
  "strings['associatedMedia']": "associatedMedia",
  "strings['associatedOccurrences']": "associatedOccurrences",
  "strings['associatedOrganisms']": "associatedOrganisms",
  "strings['associatedReferences']": "associatedReferences",
  "strings['associatedSequences']": "associatedSequences",
  "strings['associatedTaxa']": "associatedTaxa",
  "strings['basisOfRecord']": "basisOfRecord",
  "strings['bed']": "bed",
  "strings['behavior']": "behavior",
  "strings['bibliographicCitation']": "bibliographicCitation",
  "strings['biome']": "biome",
  "strings['catalogNumber']": "catalogNumber",
  "strings['class']": "class",
  "strings['classID']": "classID",
  "strings['collectionCode']": "collectionCode",
  "strings['collectionID']": "collectionID",
  "strings['collectionName']": "collectionName",
  "strings['collectionUid']": "collectionUid",
  "strings['common_name_and_lsid']": "common_name_and_lsid",
  "strings['continent']": "continent",
  "strings['country']": "country",
  "strings['countryCode']": "countryCode",
  "strings['countryConservation']": "countryConservation",
  "strings['countryInvasive']": "countryInvasive",
  "strings['county']": "county",
  "strings['dataGeneralizations']": "dataGeneralizations",
  "strings['dataProviderName']": "dataProviderName",
  "strings['dataProviderUid']": "dataProviderUid",
  "strings['dataResourceName']": "dataResourceName",
  "strings['dataResourceUid']": "dataResourceUid",
  "strings['datasetID']": "datasetID",
  "strings['datasetName']": "datasetName",
  "strings['dateIdentified']": "dateIdentified",
  "strings['datePrecision']": "datePrecision",
  "strings['disposition']": "disposition",
  "strings['duplicateStatus']": "duplicateStatus",
  "strings['dynamicProperties']": "dynamicProperties",
  "strings['earliestAgeOrLowestStage']": "earliestAgeOrLowestStage",
  "strings['earliestEonOrLowestEonothem']": "earliestEonOrLowestEonothem",
  "strings['earliestEpochOrLowestSeries']": "earliestEpochOrLowestSeries",
  "strings['earliestEraOrLowestErathem']": "earliestEraOrLowestErathem",
  "strings['earliestGeochronologicalEra']": "earliestGeochronologicalEra",
  "strings['earliestPeriodOrLowestSystem']": "earliestPeriodOrLowestSystem",
  "strings['easting']": "easting",
  "strings['endDayOfYear']": "endDayOfYear",
  "strings['establishmentMeans']": "establishmentMeans",
  "strings['eventID']": "eventID",
  "strings['eventRemarks']": "eventRemarks",
  "strings['eventTime']": "eventTime",
  "strings['family']": "family",
  "strings['familyID']": "familyID",
  "strings['fieldNotes']": "fieldNotes",
  "strings['fieldNumber']": "fieldNumber",
  "strings['footprintSRS']": "footprintSRS",
  "strings['footprintSpatialFit']": "footprintSpatialFit",
  "strings['footprintWKT']": "footprintWKT",
  "strings['formation']": "formation",
  "strings['fromLithostratigraphicUnit']": "fromLithostratigraphicUnit",
  "strings['generalisationInMetres']": "generalisationInMetres",
  "strings['generalisationToApplyInMetres']": "generalisationToApplyInMetres",
  "strings['genus']": "genus",
  "strings['genusID']": "genusID",
  "strings['geodeticDatum']": "geodeticDatum",
  "strings['geologicalContextID']": "geologicalContextID",
  "strings['georeferenceProtocol']": "georeferenceProtocol",
  "strings['georeferenceRemarks']": "georeferenceRemarks",
  "strings['georeferenceSources']": "georeferenceSources",
  "strings['georeferenceVerificationStatus']": "georeferenceVerificationStatus",
  "strings['georeferencedBy']": "georeferencedBy",
  "strings['georeferencedDate']": "georeferencedDate",
  "strings['group']": "_group",
  "strings['habitat']": "habitat",
  "strings['higherClassification']": "higherClassification",
  "strings['higherGeography']": "higherGeography",
  "strings['higherGeographyID']": "higherGeographyID",
  "strings['highestBiostratigraphicZone']": "highestBiostratigraphicZone",
  "strings['id']": "id",
  "strings['identificationID']": "identificationID",
  "strings['identificationQualifier']": "identificationQualifier",
  "strings['identificationReferences']": "identificationReferences",
  "strings['identificationRemarks']": "identificationRemarks",
  "strings['identificationVerificationStatus']": "identificationVerificationStatus",
  "strings['identifiedBy']": "identifiedBy",
  "strings['identifierRole']": "identifierRole",
  "strings['imageID']": "imageID",
  "strings['inCollection']": "inCollection",
  "strings['inDataset']": "inDataset",
  "strings['inDescribedPlace']": "inDescribedPlace",
  "strings['individualCount']": "individualCount",
  "strings['informationWithheld']": "informationWithheld",
  "strings['infraspecificEpithet']": "infraspecificEpithet",
  "strings['institutionCode']": "institutionCode",
  "strings['institutionID']": "institutionID",
  "strings['institutionName']": "institutionName",
  "strings['institutionUid']": "institutionUid",
  "strings['island']": "island",
  "strings['islandGroup']": "islandGroup",
  "strings['kingdom']": "kingdom",
  "strings['kingdomID']": "kingdomID",
  "strings['label']": "label",
  "strings['language']": "language",
  "strings['lat_long']": "lat_long",
  "strings['latestAgeOrHighestStage']": "latestAgeOrHighestStage",
  "strings['latestEonOrHighestEonothem']": "latestEonOrHighestEonothem",
  "strings['latestEpochOrHighestSeries']": "latestEpochOrHighestSeries",
  "strings['latestEraOrHighestErathem']": "latestEraOrHighestErathem",
  "strings['latestGeochronologicalEra']": "latestGeochronologicalEra",
  "strings['latestPeriodOrHighestSystem']": "latestPeriodOrHighestSystem",
  "strings['license']": "license",
  "strings['lifeStage']": "lifeStage",
  "strings['lithostratigraphicTerms']": "lithostratigraphicTerms",
  "strings['loanDestination']": "loanDestination",
  "strings['loanIdentifier']": "loanIdentifier",
  "strings['locality']": "locality",
  "strings['locationAccordingTo']": "locationAccordingTo",
  "strings['locationID']": "locationID",
  "strings['locationRemarks']": "locationRemarks",
  "strings['lowestBiostratigraphicZone']": "lowestBiostratigraphicZone",
  "strings['matchType']": "matchType",
  "strings['materialSampleID']": "materialSampleID",
  "strings['maximumDepthInMeters']": "maximumDepthInMeters",
  "strings['maximumDistanceAboveSurfaceInMeters']": "maximumDistanceAboveSurfaceInMeters",
  "strings['maximumElevationInMeters']": "maximumElevationInMeters",
  "strings['measurementAccuracy']": "measurementAccuracy",
  "strings['measurementDeterminedBy']": "measurementDeterminedBy",
  "strings['measurementDeterminedDate']": "measurementDeterminedDate",
  "strings['measurementID']": "measurementID",
  "strings['measurementMethod']": "measurementMethod",
  "strings['measurementRemarks']": "measurementRemarks",
  "strings['measurementType']": "measurementType",
  "strings['measurementUnit']": "measurementUnit",
  "strings['measurementValue']": "measurementValue",
  "strings['member']": "member",
  "strings['minimumDepthInMeters']": "minimumDepthInMeters",
  "strings['minimumDistanceAboveSurfaceInMeters']": "minimumDistanceAboveSurfaceInMeters",
  "strings['minimumElevationInMeters']": "minimumElevationInMeters",
  "strings['modified']": "modified",
  "strings['municipality']": "municipality",
  "strings['nameAccordingTo']": "nameAccordingTo",
  "strings['nameAccordingToID']": "nameAccordingToID",
  "strings['namePublishedIn']": "namePublishedIn",
  "strings['namePublishedInID']": "namePublishedInID",
  "strings['namePublishedInYear']": "namePublishedInYear",
  "strings['nameType']": "nameType",
  "strings['names_and_lsid']": "names_and_lsid",
  "strings['nick']": "nick",
  "strings['nomenclaturalCode']": "nomenclaturalCode",
  "strings['nomenclaturalStatus']": "nomenclaturalStatus",
  "strings['northing']": "northing",
  "strings['numIdentificationAgreements']": "numIdentificationAgreements",
  "strings['numIdentificationDisagreements']": "numIdentificationDisagreements",
  "strings['occurrenceDetails']": "occurrenceDetails",
  "strings['occurrenceID']": "occurrenceID",
  "strings['occurrenceRemarks']": "occurrenceRemarks",
  "strings['occurrenceStatus']": "occurrenceStatus",
  "strings['order']": "_order",
  "strings['orderID']": "orderID",
  "strings['organismID']": "organismID",
  "strings['organismName']": "organismName",
  "strings['organismQuantity']": "organismQuantity",
  "strings['organismQuantityType']": "organismQuantityType",
  "strings['organismRemarks']": "organismRemarks",
  "strings['organismScope']": "organismScope",
  "strings['originalNameUsage']": "originalNameUsage",
  "strings['originalNameUsageID']": "originalNameUsageID",
  "strings['otherCatalogNumbers']": "otherCatalogNumbers",
  "strings['ownerInstitutionCode']": "ownerInstitutionCode",
  "strings['parentEventID']": "parentEventID",
  "strings['parentNameUsage']": "parentNameUsage",
  "strings['parentNameUsageID']": "parentNameUsageID",
  "strings['photographer']": "photographer",
  "strings['phylum']": "phylum",
  "strings['phylumID']": "phylumID",
  "strings['point-0.0001']": "point_0_0001",
  "strings['point-0.001']": "point_0_001",
  "strings['point-0.01']": "point_0_01",
  "strings['point-0.02']": "point_0_02",
  "strings['point-0.1']": "point_0_1",
  "strings['point-1']": "point_1",
  "strings['pointRadiusSpatialFit']": "pointRadiusSpatialFit",
  "strings['positioningDevice']": "positioningDevice",
  "strings['positioningMethod']": "positioningMethod",
  "strings['preparations']": "preparations",
  "strings['previousIdentifications']": "previousIdentifications",
  "strings['provenance']": "provenance",
  "strings['raw_altered']": "raw_altered",
  "strings['raw_associatedOccurrences']": "raw_associatedOccurrences",
  "strings['raw_audience']": "raw_audience",
  "strings['raw_basisOfRecord']": "raw_basisOfRecord",
  "strings['raw_biome']": "raw_biome",
  "strings['raw_class']": "raw_class",
  "strings['raw_classID']": "raw_classID",
  "strings['raw_collectionName']": "raw_collectionName",
  "strings['raw_collectionUid']": "raw_collectionUid",
  "strings['raw_connectionParameters']": "raw_connectionParameters",
  "strings['raw_conservationStatuses']": "raw_conservationStatuses",
  "strings['raw_continent']": "raw_continent",
  "strings['raw_contributor']": "raw_contributor",
  "strings['raw_coordinatePrecision']": "raw_coordinatePrecision",
  "strings['raw_coordinateUncertaintyInMeters']": "raw_coordinateUncertaintyInMeters",
  "strings['raw_country']": "raw_country",
  "strings['raw_countryCode']": "raw_countryCode",
  "strings['raw_created']": "raw_created",
  "strings['raw_creator']": "raw_creator",
  "strings['raw_dataGeneralizations']": "raw_dataGeneralizations",
  "strings['raw_dataProviderName']": "raw_dataProviderName",
  "strings['raw_dataProviderUid']": "raw_dataProviderUid",
  "strings['raw_dataResourceName']": "raw_dataResourceName",
  "strings['raw_dataResourceUid']": "raw_dataResourceUid",
  "strings['raw_datasetTitle']": "raw_datasetTitle",
  "strings['raw_dateIdentified']": "raw_dateIdentified",
  "strings['raw_datePrecision']": "raw_datePrecision",
  "strings['raw_day']": "raw_day",
  "strings['raw_decimalLatitude']": "raw_decimalLatitude",
  "strings['raw_decimalLongitude']": "raw_decimalLongitude",
  "strings['raw_depth']": "raw_depth",
  "strings['raw_depthAccuracy']": "raw_depthAccuracy",
  "strings['raw_description']": "raw_description",
  "strings['raw_dynamicProperties']": "raw_dynamicProperties",
  "strings['raw_elevation']": "raw_elevation",
  "strings['raw_elevationAccuracy']": "raw_elevationAccuracy",
  "strings['raw_endDayOfYear']": "raw_endDayOfYear",
  "strings['raw_establishmentMeans']": "raw_establishmentMeans",
  "strings['raw_eventDate']": "raw_eventDate",
  "strings['raw_family']": "raw_family",
  "strings['raw_familyID']": "raw_familyID",
  "strings['raw_footprintWKT']": "raw_footprintWKT",
  "strings['raw_format']": "raw_format",
  "strings['raw_generalisationInMetres']": "raw_generalisationInMetres",
  "strings['raw_generalisationToApplyInMetres']": "raw_generalisationToApplyInMetres",
  "strings['raw_genus']": "raw_genus",
  "strings['raw_genusID']": "raw_genusID",
  "strings['raw_geodeticDatum']": "raw_geodeticDatum",
  "strings['raw_georeferencedDate']": "raw_georeferencedDate",
  "strings['raw_identifiedByIds']": "raw_identifiedByIds",
  "strings['raw_identifier']": "raw_identifier",
  "strings['raw_individualCount']": "raw_individualCount",
  "strings['raw_informationWithheld']": "raw_informationWithheld",
  "strings['raw_installationKey']": "raw_installationKey",
  "strings['raw_institutionName']": "raw_institutionName",
  "strings['raw_institutionUid']": "raw_institutionUid",
  "strings['raw_invasiveStatuses']": "raw_invasiveStatuses",
  "strings['raw_isClustered']": "raw_isClustered",
  "strings['raw_isSensitive']": "raw_isSensitive",
  "strings['raw_issues']": "raw_issues",
  "strings['raw_kingdom']": "raw_kingdom",
  "strings['raw_kingdomID']": "raw_kingdomID",
  "strings['raw_lastCrawled']": "raw_lastCrawled",
  "strings['raw_lastLoadDate']": "raw_lastLoadDate",
  "strings['raw_lastProcessedDate']": "raw_lastProcessedDate",
  "strings['raw_lft']": "raw_lft",
  "strings['raw_license']": "raw_license",
  "strings['raw_licenseType']": "raw_licenseType",
  "strings['raw_licenseVersion']": "raw_licenseVersion",
  "strings['raw_lifeStage']": "raw_lifeStage",
  "strings['raw_lifeStageLineage']": "raw_lifeStageLineage",
  "strings['raw_locality']": "raw_locality",
  "strings['raw_machineTags']": "raw_machineTags",
  "strings['raw_matchType']": "raw_matchType",
  "strings['raw_maximumDepthInMeters']": "raw_maximumDepthInMeters",
  "strings['raw_maximumDistanceAboveSurfaceInMeters']": "raw_maximumDistanceAboveSurfaceInMeters",
  "strings['raw_maximumElevationInMeters']": "raw_maximumElevationInMeters",
  "strings['raw_minimumDepthInMeters']": "raw_minimumDepthInMeters",
  "strings['raw_minimumDistanceAboveSurfaceInMeters']": "raw_minimumDistanceAboveSurfaceInMeters",
  "strings['raw_minimumElevationInMeters']": "raw_minimumElevationInMeters",
  "strings['raw_modified']": "raw_modified",
  "strings['raw_month']": "raw_month",
  "strings['raw_nameType']": "raw_nameType",
  "strings['raw_networkKeys']": "raw_networkKeys",
  "strings['raw_occurrenceStatus']": "raw_occurrenceStatus",
  "strings['raw_order']": "raw_order",
  "strings['raw_orderID']": "raw_orderID",
  "strings['raw_organismQuantity']": "raw_organismQuantity",
  "strings['raw_organismQuantityType']": "raw_organismQuantityType",
  "strings['raw_original']": "raw_original",
  "strings['raw_phylum']": "raw_phylum",
  "strings['raw_phylumID']": "raw_phylumID",
  "strings['raw_provenance']": "raw_provenance",
  "strings['raw_publisher']": "raw_publisher",
  "strings['raw_publisherTitle']": "raw_publisherTitle",
  "strings['raw_publishingCountry']": "raw_publishingCountry",
  "strings['raw_publishingOrganizationKey']": "raw_publishingOrganizationKey",
  "strings['raw_recordedBy']": "raw_recordedBy",
  "strings['raw_recordedByIds']": "raw_recordedByIds",
  "strings['raw_references']": "raw_references",
  "strings['raw_relativeOrganismQuantity']": "raw_relativeOrganismQuantity",
  "strings['raw_repatriated']": "raw_repatriated",
  "strings['raw_rgt']": "raw_rgt",
  "strings['raw_rightsHolder']": "raw_rightsHolder",
  "strings['raw_sampleSizeUnit']": "raw_sampleSizeUnit",
  "strings['raw_sampleSizeValue']": "raw_sampleSizeValue",
  "strings['raw_scientificName']": "raw_scientificName",
  "strings['raw_scientificNameAuthorship']": "raw_scientificNameAuthorship",
  "strings['raw_sensitive']": "raw_sensitive",
  "strings['raw_sex']": "raw_sex",
  "strings['raw_source']": "raw_source",
  "strings['raw_species']": "raw_species",
  "strings['raw_speciesGroup']": "raw_speciesGroup",
  "strings['raw_speciesID']": "raw_speciesID",
  "strings['raw_speciesListID']": "raw_speciesListID",
  "strings['raw_speciesSubgroup']": "raw_speciesSubgroup",
  "strings['raw_startDayOfYear']": "raw_startDayOfYear",
  "strings['raw_stateConservation']": "raw_stateConservation",
  "strings['raw_stateProvince']": "raw_stateProvince",
  "strings['raw_taxonConceptID']": "raw_taxonConceptID",
  "strings['raw_taxonRank']": "raw_taxonRank",
  "strings['raw_taxonRankID']": "raw_taxonRankID",
  "strings['raw_title']": "raw_title",
  "strings['raw_type']": "raw_type",
  "strings['raw_typeStatus']": "raw_typeStatus",
  "strings['raw_typifiedName']": "raw_typifiedName",
  "strings['raw_verbatimCoordinates']": "raw_verbatimCoordinates",
  "strings['raw_vernacularName']": "raw_vernacularName",
  "strings['raw_waterBody']": "raw_waterBody",
  "strings['raw_year']": "raw_year",
  "strings['recordNumber']": "recordNumber",
  "strings['references']": "_references",
  "strings['relatedResourceID']": "relatedResourceID",
  "strings['relationshipAccordingTo']": "relationshipAccordingTo",
  "strings['relationshipEstablishedDate']": "relationshipEstablishedDate",
  "strings['relationshipOfResource']": "relationshipOfResource",
  "strings['relationshipRemarks']": "relationshipRemarks",
  "strings['reproductiveCondition']": "reproductiveCondition",
  "strings['resourceID']": "resourceID",
  "strings['resourceRelationshipID']": "resourceRelationshipID",
  "strings['rights']": "rights",
  "strings['rightsHolder']": "rightsHolder",
  "strings['sampleSizeUnit']": "sampleSizeUnit",
  "strings['sampleSizeValue']": "sampleSizeValue",
  "strings['samplingEffort']": "samplingEffort",
  "strings['samplingProtocol']": "samplingProtocol",
  "strings['scientificName']": "scientificName",
  "strings['scientificNameAuthorship']": "scientificNameAuthorship",
  "strings['scientificNameID']": "scientificNameID",
  "strings['secondaryCollectors']": "secondaryCollectors",
  "strings['sensitive']": "sensitive",
  "strings['sensitive_dataGeneralizations']": "sensitive_dataGeneralizations",
  "strings['sensitive_day']": "sensitive_day",
  "strings['sensitive_decimalLatitude']": "sensitive_decimalLatitude",
  "strings['sensitive_decimalLongitude']": "sensitive_decimalLongitude",
  "strings['sensitive_eventDate']": "sensitive_eventDate",
  "strings['sensitive_eventID']": "sensitive_eventID",
  "strings['sensitive_eventTime']": "sensitive_eventTime",
  "strings['sensitive_footprintWKT']": "sensitive_footprintWKT",
  "strings['sensitive_locality']": "sensitive_locality",
  "strings['sensitive_locationRemarks']": "sensitive_locationRemarks",
  "strings['sensitive_month']": "sensitive_month",
  "strings['sensitive_verbatimCoordinates']": "sensitive_verbatimCoordinates",
  "strings['sensitive_verbatimEventDate']": "sensitive_verbatimEventDate",
  "strings['sensitive_verbatimLatitude']": "sensitive_verbatimLatitude",
  "strings['sensitive_verbatimLocality']": "sensitive_verbatimLocality",
  "strings['sex']": "sex",
  "strings['source']": "source",
  "strings['species']": "species",
  "strings['speciesID']": "speciesID",
  "strings['specificEpithet']": "specificEpithet",
  "strings['startDayOfYear']": "startDayOfYear",
  "strings['stateConservation']": "stateConservation",
  "strings['stateInvasive']": "stateInvasive",
  "strings['stateProvince']": "stateProvince",
  "strings['subfamily']": "subfamily",
  "strings['subgenus']": "subgenus",
  "strings['subspecies']": "subspecies",
  "strings['subspeciesID']": "subspeciesID",
  "strings['superfamily']": "superfamily",
  "strings['taxonConceptID']": "taxonConceptID",
  "strings['taxonID']": "taxonID",
  "strings['taxonRank']": "taxonRank",
  "strings['taxonRemarks']": "taxonRemarks",
  "strings['taxonomicStatus']": "taxonomicStatus",
  "strings['toTaxon']": "toTaxon",
  "strings['type']": "_type",
  "strings['typeStatus']": "typeStatus",
  "strings['typifiedName']": "typifiedName",
  "strings['userAssertions']": "userAssertions",
  "strings['userId']": "userId",
  "strings['verbatimCoordinateSystem']": "verbatimCoordinateSystem",
  "strings['verbatimCoordinates']": "verbatimCoordinates",
  "strings['verbatimDepth']": "verbatimDepth",
  "strings['verbatimElevation']": "verbatimElevation",
  "strings['verbatimEventDate']": "verbatimEventDate",
  "strings['verbatimLatitude']": "verbatimLatitude",
  "strings['verbatimLocality']": "verbatimLocality",
  "strings['verbatimLongitude']": "verbatimLongitude",
  "strings['verbatimSRS']": "verbatimSRS",
  "strings['verbatimTaxonRank']": "verbatimTaxonRank",
  "strings['vernacularName']": "vernacularName",
  "strings['videoIDs']": "videoIDs",
  "strings['waterBody']": "waterBody",
  "strings['zone']": "zone",
  "multiValues['assertionUserId']": "assertionUserId",
  "multiValues['assertions']": "assertions",
  "multiValues['contentTypes']": "contentTypes",
  "multiValues['dataHubName']": "dataHubName",
  "multiValues['dataHubUid']": "dataHubUid",
  "multiValues['duplicateJustification']": "duplicateJustification",
  "multiValues['geospatialIssues']": "geospatialIssues",
  "multiValues['identifiedByID']": "identifiedByID",
  "multiValues['imageIDs']": "imageIDs",
  "multiValues['isDuplicateOf']": "isDuplicateOf",
  "multiValues['isRepresentativeOf']": "isRepresentativeOf",
  "multiValues['lifeStageLineage']": "lifeStageLineage",
  "multiValues['machineTags']": "machineTags",
  "multiValues['multimediaLicense']": "multimediaLicense",
  "multiValues['occurrenceYear']": "occurrenceYear",
  "multiValues['occurrence_year']": "occurrence_year",
  "multiValues['outlierLayer']": "outlierLayer",
  "multiValues['recordedBy']": "recordedBy",
  "multiValues['recordedByID']": "recordedByID",
  "multiValues['soundIDs']": "soundIDs",
  "multiValues['speciesGroup']": "speciesGroup",
  "multiValues['speciesListUid']": "speciesListUid",
  "multiValues['taxonomicIssues']": "taxonomicIssues",
  "ints['day']": "day",
  "ints['decade']": "decade",
  "ints['lft']": "lft",
  "ints['month']": "month",
  "ints['taxonRankID']": "taxonRankID",
  "ints['year']": "year",
  "doubles['coordinatePrecision']": "coordinatePrecision",
  "doubles['coordinateUncertaintyInMeters']": "coordinateUncertaintyInMeters",
  "doubles['decimalLatitude']": "decimalLatitude",
  "doubles['decimalLongitude']": "decimalLongitude",
  "booleans['defaultValuesUsed']": "defaultValuesUsed",
  "booleans['hasUserAssertions']": "hasUserAssertions",
  "booleans['isInCluster']": "isInCluster",
  "booleans['spatiallyValid']": "spatiallyValid",
  "booleans['userVerified']": "userVerified",
  "dates['eventDate']": "eventDate",
  "dates['eventDateEnd']": "eventDateEnd",
  "dates['firstLoadedDate']": "firstLoadedDate",
  "dates['lastAssertionDate']": "lastAssertionDate",
  "dates['lastLoadDate']": "lastLoadDate",
  "dates['lastProcessedDate']": "lastProcessedDate",
  "dates['occurrenceYear']": "occurrenceYear",
  "dates['occurrence_year']": "occurrence_year", }

# Script generated for node SQL
occ_sql = f"""

SELECT
id,
latlng,
{','.join([k + ' ' + v for k, v in occ_fields.items()])}
FROM databox.occ_index_record  

"""
sampling_fields = {"doubles['el1002']": "el1002",
  "doubles['el1006']": "el1006",
  "doubles['el1011']": "el1011",
  "doubles['el1013']": "el1013",
  "doubles['el1019']": "el1019",
  "doubles['el1020']": "el1020",
  "doubles['el1036']": "el1036",
  "doubles['el1037']": "el1037",
  "doubles['el1038']": "el1038",
  "doubles['el1055']": "el1055",
  "doubles['el1056']": "el1056",
  "doubles['el1072']": "el1072",
  "doubles['el1073']": "el1073",
  "doubles['el1074']": "el1074",
  "doubles['el1077']": "el1077",
  "doubles['el1078']": "el1078",
  "doubles['el1079']": "el1079",
  "doubles['el1080']": "el1080",
  "doubles['el1081']": "el1081",
  "doubles['el10978']": "el10978",
  "doubles['el10979']": "el10979",
  "doubles['el10980']": "el10980",
  "doubles['el10981']": "el10981",
  "doubles['el10982']": "el10982",
  "doubles['el10983']": "el10983",
  "doubles['el10984']": "el10984",
  "doubles['el10985']": "el10985",
  "doubles['el10986']": "el10986",
  "doubles['el10987']": "el10987",
  "doubles['el10988']": "el10988",
  "doubles['el10989']": "el10989",
  "doubles['el10990']": "el10990",
  "doubles['el10991']": "el10991",
  "doubles['el10992']": "el10992",
  "doubles['el10993']": "el10993",
  "doubles['el10994']": "el10994",
  "doubles['el10995']": "el10995",
  "doubles['el10996']": "el10996",
  "doubles['el2016']": "el2016",
  "doubles['el2018']": "el2018",
  "doubles['el2042']": "el2042",
  "doubles['el2043']": "el2043",
  "doubles['el2044']": "el2044",
  "doubles['el2088']": "el2088",
  "doubles['el2089']": "el2089",
  "doubles['el2090']": "el2090",
  "doubles['el2091']": "el2091",
  "doubles['el2092']": "el2092",
  "doubles['el2093']": "el2093",
  "doubles['el2094']": "el2094",
  "doubles['el2095']": "el2095",
  "doubles['el2096']": "el2096",
  "doubles['el2097']": "el2097",
  "doubles['el2098']": "el2098",
  "doubles['el2099']": "el2099",
  "doubles['el2100']": "el2100",
  "doubles['el2101']": "el2101",
  "doubles['el2102']": "el2102",
  "doubles['el2103']": "el2103",
  "doubles['el2104']": "el2104",
  "doubles['el2119']": "el2119",
  "doubles['el2126']": "el2126",
  "doubles['el591']": "el591",
  "doubles['el598']": "el598",
  "doubles['el609']": "el609",
  "doubles['el615']": "el615",
  "doubles['el645']": "el645",
  "doubles['el647']": "el647",
  "doubles['el657']": "el657",
  "doubles['el662']": "el662",
  "doubles['el663']": "el663",
  "doubles['el665']": "el665",
  "doubles['el666']": "el666",
  "doubles['el668']": "el668",
  "doubles['el670']": "el670",
  "doubles['el671']": "el671",
  "doubles['el672']": "el672",
  "doubles['el673']": "el673",
  "doubles['el674']": "el674",
  "doubles['el676']": "el676",
  "doubles['el680']": "el680",
  "doubles['el681']": "el681",
  "doubles['el682']": "el682",
  "doubles['el683']": "el683",
  "doubles['el704']": "el704",
  "doubles['el705']": "el705",
  "doubles['el707']": "el707",
  "doubles['el708']": "el708",
  "doubles['el711']": "el711",
  "doubles['el713']": "el713",
  "doubles['el715']": "el715",
  "doubles['el718']": "el718",
  "doubles['el719']": "el719",
  "doubles['el720']": "el720",
  "doubles['el722']": "el722",
  "doubles['el725']": "el725",
  "doubles['el726']": "el726",
  "doubles['el728']": "el728",
  "doubles['el729']": "el729",
  "doubles['el730']": "el730",
  "doubles['el731']": "el731",
  "doubles['el737']": "el737",
  "doubles['el742']": "el742",
  "doubles['el743']": "el743",
  "doubles['el744']": "el744",
  "doubles['el746']": "el746",
  "doubles['el747']": "el747",
  "doubles['el749']": "el749",
  "doubles['el751']": "el751",
  "doubles['el765']": "el765",
  "doubles['el766']": "el766",
  "doubles['el767']": "el767",
  "doubles['el772']": "el772",
  "doubles['el774']": "el774",
  "doubles['el781']": "el781",
  "doubles['el782']": "el782",
  "doubles['el783']": "el783",
  "doubles['el784']": "el784",
  "doubles['el785']": "el785",
  "doubles['el786']": "el786",
  "doubles['el787']": "el787",
  "doubles['el788']": "el788",
  "doubles['el789']": "el789",
  "doubles['el790']": "el790",
  "doubles['el791']": "el791",
  "doubles['el792']": "el792",
  "doubles['el793']": "el793",
  "doubles['el794']": "el794",
  "doubles['el795']": "el795",
  "doubles['el796']": "el796",
  "doubles['el797']": "el797",
  "doubles['el798']": "el798",
  "doubles['el799']": "el799",
  "doubles['el806']": "el806",
  "doubles['el810']": "el810",
  "doubles['el814']": "el814",
  "doubles['el816']": "el816",
  "doubles['el819']": "el819",
  "doubles['el820']": "el820",
  "doubles['el827']": "el827",
  "doubles['el830']": "el830",
  "doubles['el833']": "el833",
  "doubles['el836']": "el836",
  "doubles['el841']": "el841",
  "doubles['el843']": "el843",
  "doubles['el848']": "el848",
  "doubles['el860']": "el860",
  "doubles['el862']": "el862",
  "doubles['el863']": "el863",
  "doubles['el865']": "el865",
  "doubles['el866']": "el866",
  "doubles['el867']": "el867",
  "doubles['el870']": "el870",
  "doubles['el872']": "el872",
  "doubles['el874']": "el874",
  "doubles['el875']": "el875",
  "doubles['el876']": "el876",
  "doubles['el878']": "el878",
  "doubles['el879']": "el879",
  "doubles['el881']": "el881",
  "doubles['el882']": "el882",
  "doubles['el883']": "el883",
  "doubles['el886']": "el886",
  "doubles['el887']": "el887",
  "doubles['el888']": "el888",
  "doubles['el889']": "el889",
  "doubles['el890']": "el890",
  "doubles['el891']": "el891",
  "doubles['el892']": "el892",
  "doubles['el893']": "el893",
  "doubles['el894']": "el894",
  "doubles['el898']": "el898",
  "doubles['el899']": "el899",
  "doubles['el947']": "el947",
  "doubles['el948']": "el948",
  "doubles['el949']": "el949",
  "doubles['el950']": "el950",
  "doubles['el951']": "el951",
  "doubles['el952']": "el952",
  "doubles['el954']": "el954",
  "doubles['el955']": "el955",
  "doubles['el957']": "el957",
  "doubles['el989']": "el989",
  "doubles['el996']": "el996",
  "strings['cl10000']": "cl10000",
  "strings['cl1048']": "cl1048",
  "strings['cl1049']": "cl1049",
  "strings['cl1050']": "cl1050",
  "strings['cl1051']": "cl1051",
  "strings['cl1052']": "cl1052",
  "strings['cl1053']": "cl1053",
  "strings['cl1054']": "cl1054",
  "strings['cl1057']": "cl1057",
  "strings['cl1058']": "cl1058",
  "strings['cl1059']": "cl1059",
  "strings['cl1060']": "cl1060",
  "strings['cl1061']": "cl1061",
  "strings['cl1062']": "cl1062",
  "strings['cl1063']": "cl1063",
  "strings['cl1064']": "cl1064",
  "strings['cl1065']": "cl1065",
  "strings['cl1066']": "cl1066",
  "strings['cl1067']": "cl1067",
  "strings['cl1068']": "cl1068",
  "strings['cl1069']": "cl1069",
  "strings['cl1070']": "cl1070",
  "strings['cl1071']": "cl1071",
  "strings['cl1076']": "cl1076",
  "strings['cl10829']": "cl10829",
  "strings['cl10831']": "cl10831",
  "strings['cl10832']": "cl10832",
  "strings['cl10833']": "cl10833",
  "strings['cl10834']": "cl10834",
  "strings['cl10835']": "cl10835",
  "strings['cl1084']": "cl1084",
  "strings['cl10847']": "cl10847",
  "strings['cl10848']": "cl10848",
  "strings['cl1085']": "cl1085",
  "strings['cl10872']": "cl10872",
  "strings['cl10874']": "cl10874",
  "strings['cl10900']": "cl10900",
  "strings['cl10902']": "cl10902",
  "strings['cl10903']": "cl10903",
  "strings['cl10905']": "cl10905",
  "strings['cl10906']": "cl10906",
  "strings['cl10907']": "cl10907",
  "strings['cl10908']": "cl10908",
  "strings['cl10909']": "cl10909",
  "strings['cl10910']": "cl10910",
  "strings['cl10912']": "cl10912",
  "strings['cl10921']": "cl10921",
  "strings['cl10922']": "cl10922",
  "strings['cl10923']": "cl10923",
  "strings['cl10924']": "cl10924",
  "strings['cl10925']": "cl10925",
  "strings['cl10926']": "cl10926",
  "strings['cl10927']": "cl10927",
  "strings['cl10928']": "cl10928",
  "strings['cl10929']": "cl10929",
  "strings['cl10930']": "cl10930",
  "strings['cl10933']": "cl10933",
  "strings['cl10934']": "cl10934",
  "strings['cl10935']": "cl10935",
  "strings['cl10936']": "cl10936",
  "strings['cl10937']": "cl10937",
  "strings['cl10938']": "cl10938",
  "strings['cl10939']": "cl10939",
  "strings['cl10940']": "cl10940",
  "strings['cl10941']": "cl10941",
  "strings['cl10942']": "cl10942",
  "strings['cl10943']": "cl10943",
  "strings['cl10944']": "cl10944",
  "strings['cl10945']": "cl10945",
  "strings['cl10946']": "cl10946",
  "strings['cl10947']": "cl10947",
  "strings['cl10948']": "cl10948",
  "strings['cl10955']": "cl10955",
  "strings['cl10956']": "cl10956",
  "strings['cl10957']": "cl10957",
  "strings['cl11032']": "cl11032",
  "strings['cl11033']": "cl11033",
  "strings['cl111032']": "cl111032",
  "strings['cl111033']": "cl111033",
  "strings['cl20']": "cl20",
  "strings['cl2009']": "cl2009",
  "strings['cl2010']": "cl2010",
  "strings['cl2012']": "cl2012",
  "strings['cl2013']": "cl2013",
  "strings['cl2015']": "cl2015",
  "strings['cl2020']": "cl2020",
  "strings['cl2021']": "cl2021",
  "strings['cl2022']": "cl2022",
  "strings['cl2045']": "cl2045",
  "strings['cl2048']": "cl2048",
  "strings['cl2049']": "cl2049",
  "strings['cl2050']": "cl2050",
  "strings['cl2052']": "cl2052",
  "strings['cl2076']": "cl2076",
  "strings['cl2077']": "cl2077",
  "strings['cl2078']": "cl2078",
  "strings['cl2079']": "cl2079",
  "strings['cl2080']": "cl2080",
  "strings['cl2081']": "cl2081",
  "strings['cl2083']": "cl2083",
  "strings['cl2084']": "cl2084",
  "strings['cl2085']": "cl2085",
  "strings['cl2086']": "cl2086",
  "strings['cl2087']": "cl2087",
  "strings['cl21']": "cl21",
  "strings['cl2105']": "cl2105",
  "strings['cl2109']": "cl2109",
  "strings['cl2110']": "cl2110",
  "strings['cl2111']": "cl2111",
  "strings['cl2113']": "cl2113",
  "strings['cl2115']": "cl2115",
  "strings['cl2116']": "cl2116",
  "strings['cl2117']": "cl2117",
  "strings['cl2120']": "cl2120",
  "strings['cl2124']": "cl2124",
  "strings['cl2125']": "cl2125",
  "strings['cl22']": "cl22",
  "strings['cl23']": "cl23",
  "strings['cl3']": "cl3",
  "strings['cl3003']": "cl3003",
  "strings['cl3004']": "cl3004",
  "strings['cl604']": "cl604",
  "strings['cl605']": "cl605",
  "strings['cl606']": "cl606",
  "strings['cl611']": "cl611",
  "strings['cl612']": "cl612",
  "strings['cl613']": "cl613",
  "strings['cl614']": "cl614",
  "strings['cl617']": "cl617",
  "strings['cl618']": "cl618",
  "strings['cl619']": "cl619",
  "strings['cl620']": "cl620",
  "strings['cl678']": "cl678",
  "strings['cl900']": "cl900",
  "strings['cl901']": "cl901",
  "strings['cl906']": "cl906",
  "strings['cl907']": "cl907",
  "strings['cl908']": "cl908",
  "strings['cl910']": "cl910",
  "strings['cl911']": "cl911",
  "strings['cl913']": "cl913",
  "strings['cl914']": "cl914",
  "strings['cl916']": "cl916",
  "strings['cl917']": "cl917",
  "strings['cl918']": "cl918",
  "strings['cl923']": "cl923",
  "strings['cl925']": "cl925",
  "strings['cl926']": "cl926",
  "strings['cl927']": "cl927",
  "strings['cl928']": "cl928",
  "strings['cl929']": "cl929",
  "strings['cl930']": "cl930",
  "strings['cl932']": "cl932",
  "strings['cl935']": "cl935",
  "strings['cl936']": "cl936",
  "strings['cl937']": "cl937",
  "strings['cl938']": "cl938",
  "strings['cl939']": "cl939",
  "strings['cl940']": "cl940",
  "strings['cl941']": "cl941",
  "strings['cl942']": "cl942",
  "strings['cl958']": "cl958",
  "strings['cl959']": "cl959",
  "strings['cl960']": "cl960",
  "strings['cl961']": "cl961",
  "strings['cl962']": "cl962",
  "strings['cl963']": "cl963",
  "strings['cl964']": "cl964",
  "strings['cl965']": "cl965",
  "strings['cl966']": "cl966",
  "strings['cl987']": "cl987",
  "strings['cl988']": "cl988",
  "strings['cl990']": "cl990",
  "strings['cl991']": "cl991", }
sampling_sql = f"""

SELECT
latlng,
{','.join([k + ' ' + v for k, v in sampling_fields.items()])}
FROM databox.sampling 

"""

occ_sql_node = sparkSqlQuery(
  glueContext,
  query=occ_sql,
  mapping={"occ_index_record": occ_node},
  transformation_ctx="occ",
)

samp_sql_node = sparkSqlQuery(
  glueContext,
  query=sampling_sql,
  mapping={"sampling": sampling_node},
  transformation_ctx="samp",
)

join_sql = f"""
Select occ.*, samp.{',samp.'.join(sampling_fields.values())}
from occ left outer join samp
on occ.latlng = samp.latlng
"""

join_SQL = sparkSqlQuery(
  glueContext,
  query=join_sql,
  mapping={"occ": occ_sql_node, "samp": samp_sql_node},
  transformation_ctx="join_SQL",
)

# Script generated for node Amazon S3
AmazonS3_node1649026290012 = glueContext.write_dynamic_frame.from_options(
  frame=join_SQL,
  connection_type="s3",
  format="glueparquet",
  connection_options={
    "path": "s3://ala-ecoassets/occ/parquet2/",
    "partitionKeys": [],
  },
  transformation_ctx="AmazonS3_node1649026290012",
)

job.commit()
