
library(tidyverse)
library(galah)
library(arrow)
library(assertthat)
library(pointblank)
library(ggnewscale)
library(rmapshaper)
library(magick)
library(showtext)
library(sf)
library(xml2)
library(here)

galah_config(email = Sys.getenv("ALA_EMAIL"), verbose = TRUE)